### ISSUE TITLE
Warning: Error in set_attr: ids don't have the same length than str

### ISSUE THREAD

**Issue by turgayh** [fverkroost/RStudio-Blogs#2]
I study on interactive map issue and  I find your blog post "Building Interactive World Map application ". 

I was practiced your code but It doesn't work 

Problem : 

> Warning: Error in set_attr: ids don't have the same length than str (most often, it occurs because of clipping)
  104: recordGraphics
  103: grid.draw.gTree
  101: print.ggplot
   95: func [/Users/hakan/Desktop/bitirme/R-Shiny/case study/Interactive World Map/app.R#51]
   82: origRenderFunc
   81: output$distPlot
    1: runApp

**Comment by fverkroost** [comment]
Unfortunately I cannot reproduce your error. What is the version of the ggiraph package you're using?

**Comment by taylanbt** [comment]
Hello, at first, thanks for your great work! @turgayh and I are studying on this project. We are using version 0.7.0 of gigraph package.  Thank you for your interest.

**Comment by fverkroost** [comment]
It seems that there is a bug in the latest version of ggiraph (0.7.0) that was not present in older versions (0.6.1) used when writing the code for the blog post. The error seems to be the result of setting a scale for the y-axis using “scale_y_continuous()”. I have now updated all the code on my Github to overcome this error. Please find below an overview of the changes and explanations.

To overcome this error, in the section of the worldMaps function where the plot is being built, remove the following two lines:
scale_y_continuous(limits = c(-60, 90), breaks = c()) + 
scale_x_continuous(breaks = c()) + 

These lines would limit the y-axis range from [-60, 90] (to remove Antarctica from the map) and remove tick labels on both x- and y-axes. Another way to go about removing the tick labels now while preserving the rest of the plot layout would be to change the my_theme function definition into the following:
my_theme <- function () { 
    theme_bw() + theme(axis.title = element_blank(),
                       axis.text = element_blank(),
                       axis.ticks = element_blank(),
                       panel.grid.major = element_blank(), 
                       panel.grid.minor = element_blank(),
                       panel.background = element_blank(), 
                       legend.position = "bottom",
                       panel.border = element_blank(), 
                       strip.background = element_rect(fill = 'white', colour = 'white'))
  }

To remove Antarctica from the maps, we can subset our plotting data to exclude latitudes outside the range of [-60, 90]. Normally, we can do this by setting the limits in either of the functions scale_y_continuous() or coord_cartesian(), but these result in errors in combination with geom_polygon_interactive() for the latest versions of ggiraph. To subset the data to exclude Antarctica, change “data = world_data” within geom_polygon_interactive() to “data = subset(world_data, lat >= -60 & lat <= 90)”.

**Comment by iago-pssjd** [comment]
Hello,

Today I have yet the same problem. If this is a bug in `ggiraph`, was it reported to them? May it have something to do with https://github.com/davidgohel/ggiraph/issues/156?
