### ISSUE TITLE
Interactive maps question

### ISSUE THREAD

**Issue by mountaingoat19** [fverkroost/RStudio-Blogs#3]
Hi,

Your [example](https://rviews.rstudio.com/2019/10/09/building-interactive-world-maps-in-shiny/) is very helpful, but in my case, the gradation (5 to 20 for you) varies when I change a condition. I would like it to stay the same do you have an idea how would I do that?

Thanks

**Comment by fverkroost** [comment]
Hi mountaingoat19, 

Thanks for reaching out. In my example, the intention is that the (limits of the) color scale change with the conditions depending on the minimum and maximum data values. If you would like to set fixed limits on the color bar instead, then you could change the line
```
scale_fill_gradientn(colours = brewer.pal(5, "RdBu"), na.value = 'white')
```
in the final section of the ```worldMaps``` function to the following:
```
scale_fill_gradientn(colours = brewer.pal(5, "RdBu"), na.value = 'white', limits = c(lwr, upr))
```
where ```lwr``` and ```upr``` represent the fixed lower respectively upper limits chosen by you.

Hope this helps,
Florianne
